### ISSUE TITLE
0.1.11 generating bad go code for untyped parameters

### ISSUE THREAD

**Issue by AlbinTheander** [oden-lang/oden#21] opened 2015-11-29 16:08 UTC
I was playing around with 0.1.11and the following code generates non-valid go code:

https://gist.github.com/AlbinTheander/7d3b4451943927b819c0

It I guess it's because one parameter is never used anywhere and thus there is no type being bound to it.

Since the function names contain the types, it generates ".0" in the middle of the name, which is not a valid identifier.

**Comment by owickstrom** [comment] 2015-11-29 17:20
Right, this should be https://github.com/oden-lang/oden/blob/master/odenc/inferencer/generalizeo.rkt somehow missing to replace logic variables with type variables (`g123` etc).

**Comment by owickstrom** [comment] 2015-11-29 21:44
Got this nailed down with a test now, hoping to fix it tonight. :)

**Comment by owickstrom** [comment] 2015-11-29 22:47
So it seems it's the `let` messing the monomorphization up. This works: https://oden-playground.herokuapp.com/p/5dbd83f0c3ed5246acb50e4470287a3a

**Comment by AlbinTheander** [comment] 2015-11-30 06:29
I don't think so. In that code, `first` isn't called at all, so it's removed. This code does the same but uses first and it fails:

https://oden-playground.herokuapp.com/p/45de7e4dc58ea142aa73e4a7fdd2aba5

**Comment by owickstrom** [comment] 2015-11-30 06:31
https://github.com/oden-lang/oden/commit/ba6da5e4cb96771708a39acc90b285922af5961f also makes the `pair`/`first` functions work, but only without `let`: 

```scheme
(pkg main)

(import "fmt")

(define (pair x y)
  (fn (f) (f x y)))

(define (first p)
  (p (fn (x y) x)))

(define (main)
  (fmt.Println (first (pair "a" "b"))))
;=> "a"
```

**Comment by owickstrom** [comment] 2015-11-30 06:34
You are correct! However, the last commits on master fixes that. Maybe I should push that to the playground. :)

**Comment by AlbinTheander** [comment] 2015-11-30 08:12
Ok. Missed those commits. It seems to work nicely now, apart from the let.

Makes it possible to implement lists through functions. :-)

**Comment by owickstrom** [comment] 2015-11-30 08:23
I pushed them this morning, so my bad. :)

Yeah, that's a cool example you did! Couldn't resist adding it to the experiments: https://github.com/oden-lang/oden/blob/master/experiments/not-working/streams.oden

**Comment by owickstrom** [comment] 2015-12-01 06:28
OK, so the problem can be reduced to the following example ([Playground link](https://oden-playground.herokuapp.com/p/68b11a94165ec7c6137b736517ba32d9)):

```scheme
(pkg main)

(import fmt)

(define (identity x) x)
(define (main) (fmt.Println (let ([my-id identity]) (my-id "Foo"))))
```

The let that introduces the `my-id` binding breaks the monomorphization. The current output Go code is:

```go
package main

// imports
import "fmt"

// monomorphed
func identity_inst_var__of__g31_to_var__of__g31(x var_g31) var_g31 {
	return x
}

// definitions
func main() {
	fmt.Println((func() string {
		var myId func(var_g31) var_g31 = identity_inst_var__of__g31_to_var__of__g31
		return myId("Foo")
	}()))
	return
}
```

The problem is that all instances of `my-id` must be monomorphed in the `let` (as it may close over parent bindings) and all references to `identity` must be monomorphed based on the let monomorphization. That would mean that this example ([Playground link](https://oden-playground.herokuapp.com/p/dcc3d6900378e84c4f94d7195dfd176b)):

```scheme
(pkg main)

(import fmt)

(define (identity x) x)
(define (main) (fmt.Println (let ([my-id identity]) ((my-id my-id) "Foo"))))
```

... would generate something like this (don't mind the simplified names):

```go
package main

// imports
import "fmt"

// monomorphed
func identity_inst_fn_to_fn(x func(string) string) func(string) string {
	return x
}
func identity_inst_string_to_string(x string) string {
	return x
}

// definitions
func main() {
    fmt.Println((func() string {
        // monomorphed
        var myId_inst_fn_to_fn func(func(string) string) func(string) string = identity_inst_fn_to_fn
        return (func() string {
            // monomorphed
            var myId_inst_string_to_string func(string) string = identity_inst_string_to_string
            return myId_inst_fn_to_fn(myId_inst_string_to_string)("Foo")
        }())    
    }()))
    return
}
```

@AlbinTheander What do you think?

**Comment by owickstrom** [comment] 2015-12-04 06:27
Got this working now, it's on master and in the 0.1.12 release. I hope you'll find the bugs, @AlbinTheander. :grinning: 

These Playground examples that we have talked about work now:
* https://oden-playground.herokuapp.com/p/68b11a94165ec7c6137b736517ba32d9
* https://oden-playground.herokuapp.com/p/f66ef8972e7aadb6f385001dee59d27f

**Comment by owickstrom** [comment] 2015-12-04 06:28
I'm closing this for now, if we find something we'll open another issue.

**Closed by owickstrom** 2015-12-04 06:28 UTC
Labels: bug
