### ISSUE TITLE
Support Stack

### ISSUE THREAD

**Issue by Xe** [oden-lang/oden#51] opened 2016-02-26 22:19 UTC
It'd be nice to support [Stack](https://github.com/commercialhaskell/stack) instead of cabal sandboxes.

**Comment by owickstrom** [comment] 2016-02-26 22:24
Yeah. I haven't had the time to check it out but I really want to. Do you have any experience in setting it up? There's some funky business going in Oden with building and linking a Go library into the Haskell executable which might be a bit tricky.

**Comment by aspidites** [comment] 2016-02-27 15:05
So I just started messing with this about five minutes ago. The first thing I ran into is warnings about `exposed-modules` being defined in an improper section. Specifically the Oden.CLI modules, since it's under an `executable` section. Three solutions I can think of would be to have an oden-cli library section which cli executable relies on, or simply move the entire Oden.CLI module into src and expose it from there. Finally, those modules could simply not be exposed, but I doubt that's desirable. 

I'm going to see if I can ignore the warning and continue from that, but did want to mention it.

**Comment by owickstrom** [comment] 2016-02-27 15:08
Yeah, that is strange. Not sure why they're there, it's only the cli executable that needs them anyway.

Cool, just let me know if there's anything I can do to help.

**Comment by aspidites** [comment] 2016-02-27 15:31
So I'm able to start building, but get failures. I've tried the following different invocations with their respective results:
- `stack build` - failure
- `stack build cli` - no failure, but no executable produced
- `stack build oden` - failure
- `cabal build` - failure
- `cabal build oden` - no failure but no executable produced
- `cabal build cli` - failure

In each of the failure cases, the error message is this:
```
Warning: the following files would be used as linker inputs, but linking is not being done: dist/go-lib/importer.a
Linking dist/build/cli/cli ...
/home/aspidites/projects/oden/dist/build/libHSoden-0.3.0-DXbOQy0U1PA4wRDQMKimJK.a(Go.o):(.text+0x16dfd): undefined reference to `GetPackageObjects'
collect2: error: ld returned 1 exit statu
```

**Comment by owickstrom** [comment] 2016-02-27 15:35
Ah, sorry. There's the Go library that needs to be built first, and the Makefile takes care of that right now. If you run `make libs` first, does it work then? I've been meaning to integrate that part in a custom Setup.hs script.

**Comment by aspidites** [comment] 2016-02-27 15:50
Sorry, before I started messing with this, I did the normal instructions with make, so that file exists. Just seems neither cabal nor stack know how to find it?

I'm fiddling with extra-lib-dirs at the moment to see if that solves anything.

**Comment by owickstrom** [comment] 2016-02-27 15:53
All right. Do you get the same warning about "linking not being done" when running `cabal build oden`?

**Comment by owickstrom** [comment] 2016-02-27 16:02
What OS are you running btw?

**Comment by aspidites** [comment] 2016-02-27 16:03
Not when running `cabal build oden`, but when running `cabal build cli`.
I'm on Arch linux. Namely:
```
$ uname -a
Linux vapor 4.4.2-1-ARCH #1 SMP PREEMPT Thu Feb 18 12:11:13 CET 2016 x86_64 GNU/Linux
```

**Comment by owickstrom** [comment] 2016-02-27 16:13
Ok. Haven't tried that much on Linux lately, but if I remember correctly the only way I got it to work on Ubuntu was to have a custom `ghc` build (see `make cli` and https://github.com/oden-lang/oden/blob/master/Makefile#L46). This whole business with linking the Go library have been a mess so far. If you can get it to work without the Makefile on Linux I'll be forever grateful! :) It works on OS X but with the same warning.

**Comment by owickstrom** [comment] 2016-02-27 16:14
I think there's another route with compiling the Go library as `-buildmode c-shared` and linking to the dynamic library, but I'm not sure how to go about distributing that (ld library paths etc...). It's not my strongest area.

**Comment by aspidites** [comment] 2016-02-27 16:18
From https://github.com/andrep/hoc/issues/12 :

> The deeper cause (the reason it's being done that way) is that it is a 
reasonably simple way of getting Cabal to accept 
an object file as an input to the build process.  Just removing the offending 
line won't work unless we also cause it to 
be linked in to the build products (presumably in a post-build hook in the 
Setup file).

I think I've seen elsewhere that this is a known issue as well. Unfortunately, it's not my strong suit either ;-). I'll take a look at your suggestions and report back.

**Comment by owickstrom** [comment] 2016-02-27 16:29
All right. Thank you for putting effort into this!

**Comment by aspidites** [comment] 2016-02-27 16:36
Yeah, I think the linking issues will have to be solved before building with stack will make sense (would love to be proven wrong). For posterity though, getting the initial config for stack was rather easy:

```
cd oden
stack init --resolver=lts-5.4
```
Then add "- aeson-0.11.0.0" to the "extra-deps" section (line 11) for me.

You can use aeson-0.10, but You'd have to use the nightly resolver and would still have the bit in extra-deps. Plus there's that whole performance regression thing with that version.

**Comment by aspidites** [comment] 2016-02-27 16:37
That said, I'm definitely keeping an eye out on this project.

**Comment by owickstrom** [comment] 2016-02-27 16:42
Yep, you're right. OK, then it's looking good on the stack parts at least. :)

Please do, there's surely other things to work on if you want to contribute as well.

**Comment by codygman** [comment] 2016-03-10 05:04
Glad you got this resolved mostly. I have oden built with stack locally but haven't had a chance to PR :/

**Comment by owickstrom** [comment] 2016-03-17 08:23
@codygman Have you gotten the Go build and linking stuff working in a custom `Setup.hs` build as well? Would love to see your stack work in a PR when you're ready. :+1:

**Comment by codygman** [comment] 2016-03-23 13:32
@owickstrom No I have not, I was still using the Makefile but with stack instead of cabal. I'll see if I can do that later this week or during the weekend.

**Comment by owickstrom** [comment] 2016-04-24 14:57
I did a take on the Stack support, available in https://github.com/oden-lang/oden/tree/stack-support. I have only had the time to run it on Linux so far, there's probably some tweaks needed for OS X. I haven't got all Stack commands working properly with the linking stuff so the Makefile wraps them and adds `LD_LIBRARY_PATH`. Note that the *importer* package written in Go is now dynamically linked instead of statically linked into `oden`.

If any of you would like to give this a try on any OS I'd be very grateful. Thanks!

**Comment by owickstrom** [comment] 2016-04-30 09:43
I've tried this on OS X and Ubuntu Linux and it works properly, I think. Also the Travis build uses Stack now. I'm closing the issue. Thanks for your input!

**Closed by owickstrom** 2016-04-30 09:43 UTC
Labels: build-system
